//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlickClick.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5bPRDveArdI6v6jh+8H3rKZIxbNm0NZw0nKJOImJURsDsG08EhdtUpWbdHyxNwf4l5KUGgmXuoi+3Pulm" +
            "j+rNy9WmZkRNW9Ugic0i8oie90=")]
        public string FLICKR_KEY {
            get {
                return ((string)(this["FLICKR_KEY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aiRa2ZFKzL5WBr7sqn44EI5cIBnnWrw+xdqOoG1nePPFZYY/hdfipII/L1NC+G1i")]
        public string FLICKR_SECRET {
            get {
                return ((string)(this["FLICKR_SECRET"]));
            }
        }
    }
}
